# fly.toml app configuration file generated for cda-weather-arms-bot on 2025-07-07T13:11:05+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cda-weather-arms-bot'
primary_region = 'sin'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  cpu_kind = 'shared'
  memory = '512mb'
  cpus = 1

[[restart]]
  policy = "always"
  retries = 5
  processes = ["app"]

[[services]]
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443